### PR TITLE
Bug 1473155: 30% review

### PR DESCRIPTION
**Pull request by djmitche**
There's a bunch left to do here, but I feel like the direction is clear from this much.  What do you think?

Big stuff to do:
 * *styling* - I'd like the left side to be in a "code" font, possibly with some syntax coloring (at least for comments).  The right needs to be rendered in markdown, and I'd like to fix the vertical alignment of the titles (maybe I'll just use boldface for the title?); and find a more consistent way to display annotations like range or format.
 * Support refs
 * <strike>Remove bootstrap</strike>
 * <strike>Remove use of the CodeTooltip</strike>
 * Responsiveness (probably just with min-width)
 * Bugs or issues for the remaining unsupported json-schema features (dependencies, etc.)

I could use a bit of help with the styling, to be honest :)

### CODE REVIEW

**Review by helfi92 — COMMENTED** [review]
> I'd like the left side to be in a "code" font, possibly with some syntax coloring (at least for comments).

Have a look at @mozilla-frontend-infra/components, namely the `Code` component. It can highlight comments.

screen shot 2019-01-02 at 3 02 14 pm


> The right needs to be rendered in markdown

`react-schema-viewer` has a widget `Markdown` that takes care of styling markdown content. It currently does:

```jsx
dangerouslySetInnerHTML={{
  __html: markdown().renderInline(this.props.children)
}}
```

You can start using the `.render` function instead of `renderInline` to render a block.

```jsx
__html: markdown().render(this.props.children)
```

Additionally, you may want to use `turndown` and `renderToStaticMarkup` to render markdown from html. Something like:

```jsx
// This is used to transform jsx into a string
import { renderToStaticMarkup} from 'react-dom/server';
// This is used to convert html to markdown
import TurndownService from 'turndown';
// This is used to display markdown
import Markdown from '../../widgets/Markdown';

export default class SchemaRow extends React.Component {
  constructor(props) {
    super(props);

    this.turndownService = new TurndownService();
  }

  // ...

  description = () => {
    // ...
    const markup = (
      <td width="60">...</td>
    );

    return this.turndownService.turndown(renderToStaticMarkup(markup));
  };

  // ...

  render() {
    const description = this.description();
    // ...

    return (
      // ...
      <Markdown>{description}</Markdown>
    );
  }
}
```

> I'd like to fix the vertical alignment of the titles (maybe I'll just use boldface for the title?)

Boldface is a good enough solution imo.

**Comment by djmitche** [comment]
Thanks!  I think the Code component would require that all of the output be in a single block of text, which won't be the case here.  It should be relatively straightforward to get the coloring going "manually".

I am intending to use the Markdown widget.  But, I'm not sure how Turndown would help?  It looks like I would take JSX, convert it to HTML, then to Markdown, and then render that?  Why not just render the JSX?

**Comment by helfi92** [comment]
> I am intending to use the Markdown widget. But, I'm not sure how Turndown would help? It looks like I would take JSX, convert it to HTML, then to Markdown, and then render that? Why not just render the JSX?

You can definitely always render directly the `jsx` but you will have to take care of styling the jsx to resemble a markdown file (assuming that's what you wanted). The only reason I suggested `turndown` is so that you can feed the output to the `Markdown` component since it only takes markdown as input.

**Review by imbstack — COMMENTED** [review]
I'm going to trust @helfi92 to review this. Looks cool so far!

**Comment by ccooper** [comment]
This was pegged for our intern, but is effectively back in the pool now.

**Comment by djmitche** [comment]
We can close this for now and track work in https://bugzilla.mozilla.org/show_bug.cgi?id=1473155

**Pull request closed without merging**
