### PR TITLE
Fix: Make tooltip have position absolute

### PR DESCRIPTION
**Pull request by Vane237**

### CODE REVIEW

**Comment by Vane237** [comment]
Screen Shot 2019-11-08 at 11 10 59

**Review by helfi92 — APPROVED** [review]

**Comment by helfi92** [comment]
Released in react-schema-viewer@3.2.2 🎉

**Comment by helfi92** [comment]
@Vane237 I tried testing this on the Taskcluster UI but I'm not able to see the tooltip. Can you replicate?

**Comment by helfi92** [comment]
You can test this by running `yarn add react-schema-viewer` inside the `ui` directory of Taskcluster.

**Comment by Vane237** [comment]
Sure
Let me try too

**Comment by Vane237** [comment]
Screen Shot 2019-11-08 at 15 11 43

It works after updating it

**Comment by helfi92** [comment]
Ohhh, I must have done something wrong. Do you want to open a pull request to update the react-schema-viewer version?

**Comment by Vane237** [comment]
Sure I do

**Pull request merged**
