### PR TITLE
rename SchemaTable -> SchemaViewer to match README, package name

### PR DESCRIPTION
**Pull request by djmitche**
I'm assuming this was accidental, but please lmk if there's a reason for it!

### CODE REVIEW

**Comment by helfi92** [comment]
I'm thinking we can just take care of the issue in https://github.com/taskcluster/react-schema-viewer/issues/22. Feel free to close if you agree.

**Comment by djmitche** [comment]
Why not just land this now?  I could make #22 based on this commit, if you prefer, I just don't see why..

**Review by helfi92 — COMMENTED** [review]
The original idea behind naming it `SchemaTable` was to allow extending the library in the future to allow viewing a schema in other formats (e.g, graph instead of a table). Since we only display the schema in a table format for now, the default import simply pulls SchemaTable.

**Comment by helfi92** [comment]
I think it should be more like

```jsx
import { SchemaTable } from 'react-schema-viewer';
```

with #22, we can probably do:

```jsx
import { JSONSchemaTable, JoiSchemaTable } from 'react-schema-viewer';
```

Let me know what you think.

**Comment by djmitche** [comment]
Ah, OK, that makes a lot of sense.  Thanks!

**Pull request closed without merging**
